### ISSUE TITLE
README and book quick start no longer work for `rustc 1.89.0-nightly`

### ISSUE THREAD

**Issue by BowTiedRadone** [loiclec/fuzzcheck-rs#53]
Following the `Quick Start` tutorial won't compile with `rustc 1.89.0-nightly`:
```
error[E0557]: feature has been removed
 --> src/lib.rs:1:30
  |
1 | #![cfg_attr(fuzzing, feature(no_coverage))]
  |                              ^^^^^^^^^^^ feature has been removed
  |
  = note: renamed to `coverage_attribute`

error[E0658]: the `#[coverage]` attribute is an experimental feature
 --> src/lib.rs:4:28
  |
4 | #[cfg_attr(fuzzing, derive(fuzzcheck::DefaultMutator))]
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #84605 <https://github.com/rust-lang/rust/issues/84605> for more information
  = help: add `#![feature(coverage_attribute)]` to the crate attributes to enable
  = note: this compiler was built on 2025-05-19; consider upgrading it if it is out of date
  = note: this error originates in the derive macro `fuzzcheck::DefaultMutator` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: the `#[coverage]` attribute is an experimental feature
  --> src/lib.rs:11:28
   |
11 | #[cfg_attr(fuzzing, derive(fuzzcheck::DefaultMutator))]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #84605 <https://github.com/rust-lang/rust/issues/84605> for more information
   = help: add `#![feature(coverage_attribute)]` to the crate attributes to enable
   = note: this compiler was built on 2025-05-19; consider upgrading it if it is out of date
   = note: this error originates in the derive macro `fuzzcheck::DefaultMutator` (in Nightly builds, run with -Z macro-backtrace for more info)

```
Updating this way fixed the issue:

```diff
- #![cfg_attr(fuzzing, feature(no_coverage))]
+ #![cfg_attr(fuzzing, feature(coverage_attribute))]
```
